name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile.dev --tag smartwhale/docker-react
    - name: Run the tests
      run: docker run smartwhale/docker-react npm run test -- --coverage --watchAll=false
